### ISSUE TITLE
[Glyph Migration] Some stuff was broken

### ISSUE THREAD

**Issue by impallari** [impallari/Dosis#2]
Fix the broken stuff before releasing, see https://github.com/impallari/Dosis/pull/1

**Comment by m4rc1e** [comment]
@davelab6 @impallari I'll fix this today.

Were you happy with the anchors on this font?

Cheers,
Marc

**Comment by m4rc1e** [comment]
We have some inconsistencies:

**1.**
![screen shot 2016-12-06 at 09 51 59](https://cloud.githubusercontent.com/assets/7525512/20918923/af412980-bb99-11e6-9086-74fbecd671d4.png)

**2.**
![screen shot 2016-12-06 at 09 53 01](https://cloud.githubusercontent.com/assets/7525512/20918953/cb933eb6-bb99-11e6-8a51-2b37e5053e7a.png)

We have two different approaches here. The correct way, no1, uses anchors to position the accents (Vietnamese and new lang extension). no2 is just outlines (legacy glyphs). Neither approaches match. 

Even the design of the accents is different by using both approaches.

**1.**
![screen shot 2016-12-06 at 09 57 53](https://cloud.githubusercontent.com/assets/7525512/20919107/7c546be4-bb9a-11e6-840d-ee603e4e7ff9.png)

**2.**
![screen shot 2016-12-06 at 09 57 39](https://cloud.githubusercontent.com/assets/7525512/20919116/824bdeba-bb9a-11e6-802c-6fb831e48dc3.png)



I recommend we fix all the no2 glyphs so they use composites and anchors. This will bring more consistency across the family. This is at least a day of work I reckon.

**Comment by davelab6** [comment]
Dosis should be postponed until January for a pr to Google Fonts 😄
